<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '- select status -' => '@@- выберите статус -@@',
    'Are you sure you want to delete this item?' => '@@@@',
    'Data' => '@@Дата@@',
    'Date' => '@@Дата@@',
    'Delete' => '@@Удалить@@',
    'Email' => '@@Email@@',
    'ID' => '@@ID@@',
    'Message' => '@@Сообщение@@',
    'Name' => '@@Имя@@',
    'Order #{orderID}' => '@@Заказ №{orderID}@@',
    'Orders' => '@@Заказы@@',
    'Phone' => '@@Телефон@@',
    'Reset' => '@@Очистить@@',
    'Search' => '@@Поиск@@',
    'Search Orders' => '@@Поиск Заказов@@',
    'Set as Done' => '@@Пометить как обработанный@@',
    'Set as New' => '@@Пометить как новый@@',
    'Status' => '@@Статус@@',
    'Total Cost' => '@@Сумма@@',
    'New' => 'Новый',
    'Processed' => 'Обработан',
    'Reviewed' => 'Просмотрен',
];
