<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '- select category -' => '@@- выберите категорию -@@',
    '- select status -' => '@@- выберите статус -@@',
    'Category' => '@@Категория@@',
    'Create' => '@@Добавить@@',
    'Create Product' => '@@Добавить Продукт@@',
    'Date' => '@@Дата@@',
    'Description' => '@@Описание@@',
    'ID' => '@@ID@@',
    'If empty it will be generated from name' => '@@Если не указать - будет сгенерировано с имени@@',
    'Image' => '@@Фото@@',
    'Images' => '@@Доп. Фото@@',
    'Meta Description' => '@@Meta Описание@@',
    'Meta Keywords' => '@@Meta Ключевые слова@@',
    'Name' => '@@Название@@',
    'Price' => '@@Цена@@',
    'Products' => '@@Товары@@',
    'Reset' => '@@Очистить@@',
    'Search' => '@@Искать@@',
    'Search Products' => '@@Поиск Товаров@@',
    'Slug' => '@@URL@@',
    'Status' => '@@Статус@@',
    'Update' => '@@Редактировать@@',
    'Update {modelClass}: ' => '@@Редактировать {modelClass}: @@',
    'View on site' => '@@Посмотреть на сайте@@',
    'Browse' => 'Выбрать',
    'Delete' => 'Удалить',
];
