<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Clear Cart' => 'Очистить Коризну',
    'Total cost' => 'Стоимость',
    'Your order number: {orderNumber}' => '',
    'Your request was successfully ordered. We will contact you soon' => 'Ваш заказ был успешно оформлен. Мы скоро с Вами свяжемся',
    'Cart' => 'Корзина',
    'Category' => 'Категория',
    'Continue shopping' => 'Продолжить покупки',
    'Count of products' => 'Количество товаров',
    'Image' => 'Фото',
    'It can bu used when you are contact us to know some information about your order' => 'Это может быть использовано для получения информации о заказе',
    'Order' => 'Оформление заказа',
    'Ordered successful' => 'Заказ успешно оформлен',
    'Price' => 'Цена',
    'Product' => 'Товар',
    'Reset' => 'Очистить',
    'Summary' => 'Информация',
];
