<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Home' => 'Главная',
    'Last products' => 'Последние товары',
    'Please contact us if you think this is a server error. Thank you.' => 'Пожалуйста, свжитесь с нами если Вы считаете, что это серверная ошибка. Спасибо.',
    'The above error occurred while the Web server was processing your request.' => 'Эта ошибка произошла при обработке вашего запроса',
];
